# kustomization.yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../base

namespace: default
# create patches for the deployment without changing the original file
patches:
- path: ingress.yaml
  target:
    kind: Ingress
    name: caddy-ingress